name: build

on:
  push:
    branches: [ master, develop ]
  pull_request:
    branches: [ master, develop ]

jobs:
  test:
    strategy:
      matrix:
        os: [ubuntu-latest]
        python: [3.7, 3.8]
    runs-on: ${{ matrix.os }}

    steps:
    - uses: actions/checkout@v2
    - name: Set up Python ${{ matrix.python }}
      uses: actions/setup-python@v1
      with:
        python-version: ${{ matrix.python }}
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -e .
        pip install -r requirements_test.txt
    - name: Lint with pre-commit
      run: |
        pre-commit run --all-files
    - name: Test with pytest
      run: |
        pytest -p no:spark -m "not spark_test"
        
  armv64_py37_job:
      name: Build and Test for arm64 with py37
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && apt-get -y install python3.7 curl git && \
              ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && export DEBIAN_FRONTEND=noninteractive && apt-get install -y tzdata && dpkg-reconfigure --frontend noninteractive tzdata && \
              apt-get -y install software-properties-common && add-apt-repository ppa:deadsnakes/ppa && apt-get -y update && \
              apt install -y python3.7-venv && python3.7 -m venv venv37 && source venv37/bin/activate && \
              python3.7 -m pip install --upgrade pip && \
              python3.7 --version && \
              uname -m && \
              whoami && \
              pwd && \
              ls && \
              python3.7 -m pip install --upgrade pip && \
              python3.7 -m pip install -e . && \
              python3.7 -m pip install -r requirements_test.txt && \
              python3.7 -m pytest -p no:spark -m "not spark_test" && \
              deactivate'
  armv64_py38_job:
      name: Build and Test for arm64 with py38
      runs-on: ubuntu-20.04
      steps:
        - uses: actions/checkout@v2
        - name: Set up QEMU
          id: qemu
          uses: docker/setup-qemu-action@v1
        - name: Install and Run tests
          run: |
            docker run --rm -v ${{ github.workspace }}:/ws:rw --workdir=/ws \
              arm64v8/ubuntu:20.04 \
              bash -exc 'apt-get update && apt-get -y install python3 python3-pip python3-venv curl git && \
              ln -fs /usr/share/zoneinfo/America/New_York /etc/localtime && export DEBIAN_FRONTEND=noninteractive && apt-get install -y tzdata && dpkg-reconfigure --frontend noninteractive tzdata && \
              python3 -m pip install virtualenv && python3 -m venv py38-venv && \
              source py38-venv/bin/activate && \
              python3 -m pip install --upgrade pip && \
              python3 --version && \
              uname -m && \
              whoami && \
              pwd && \
              ls && \
              python3 -m pip install --upgrade pip && \
              python3 -m pip install -e . && \&& \
              python3 -m pip install -r requirements_test.txt && \
              python3 -m pytest -p no:spark -m "not spark_test" && \
              deactivate'
